### ISSUE TITLE
anyone can help me？ i can't mint nft at moonriver nftbrawl

### ISSUE THREAD

**Issue by daring5920** [blocklords/seascape-smartcontracts#5]
tips:

Error: VM Exception while processing transaction: revert NFT Rush: Failed to verify quality signature

this tx :0x09cf16237220f09088b2e1fdf981611ff23b6d8c02ff09d252f4e94ec42f9551

**Comment by daring5920** [comment]
![imsrUDAU](https://user-images.githubusercontent.com/21689738/134831944-5ae48273-91db-4a24-a127-408c00d67437.jpg)

**Comment by ahmetson** [comment]
Hey, sorry for a long reply. With game related issues you should contact to support@seascape.network
